#!/bin/bash

aide () {
	echo "find the mount possibility" 
	echo 
	exit
}

case "$1" in 
	-h) aide
	;;
esac

#Récupération du nom des partitions montée  
var=`lsblk -l -o NAME,TYPE|grep [pr][ao][rm] |sed "s/part//g" |sed "s/rom//g" | tr '\n' ' '`
part='' #Partition à écrire dans fstab

for i in $var 
do 
	# Récupération du nom du device b,c,d,etc 
	name_device=`ls /dev | grep s[dr][b-z][1-9]|cut -c3`
	
	# Récupération device ou cdrom
	device_or_cd=`ls /dev | grep s[dr][b-z][1-9]|cut -c2`
	
	#Récupération du nombre de partition
	nb_part=`ls /dev | grep -c s$device_or_cd$name_device[1-9]`
	
	if grep -q "$i" /etc/fstab
	then part=$part
	else 
	
		if [ "$nb_part" = "1" ]
		then
			echo $device_or_cd
			echo $name_device
			echo $nb_part
			#echo $i
			#if [ $device ] 
			#part=$part'/dev/'$i" /mnt/flash auto noauto,relatime,noexec,nosuid,user,umask=027,flush 0 0$'\n'"
			#makedir=$makedir"mkdir -p /mnt/flash;"
		else 
			echo $device_or_cd
			echo $name_device
			echo $nb_part
			#echo $nb_part
			#echo $i
			#part=$part'/dev/'$i" /mnt/sauvegarde auto noauto,relatime,noexec,nosuid,user,umask=027,flush 0 0$'\n'"
			#makedir=$makedir"mkdir -p /mnt/sauvegarde;"
		fi
		
		
	fi
done

if [ "$part" != '' ] 
then 
	/bin/su -c "echo $part >> /etc/fstab;$makedir"
fi

exit
