#!/bin/bash

aide () {
	echo "find the mount possibility" 
	echo 
	exit
}

case "$1" in 
	-h) aide
	;;
esac

#var=findmnt | grep "/dev/s[d|r]"
#df --output=source,target |grep " /[ |b|h|m]"
#lsblk -l -o PATH,MOUNTPOINT,TYPE|grep part|sed "s/part//g"

#lsblk -l |grep "[0-9] [part|rom]" > ~/bin/tmp

#var="${lsblk -l -o PATH,MOUNTPOINT,TYPE|grep part |sed "s/part//g"}"
#echo $var
#var="\""`lsblk -l -o PATH,MOUNTPOINT,TYPE|grep part |sed "s/part//g" | tr '\n' '"' | sed "s/\"/\" \"/g"`"\""
echo "\""`lsblk -l -o PATH,MOUNTPOINT,TYPE|grep part |sed "s/part//g" | tr '\n' '"'` #| sed "s/\"/\" \"/g"`"\""


#for i in "$var"; do echo $i ; done 



exit 
